In [25]:
from datasets.affect.get_data import get_dataloader
import numpy as np
import random
import pickle
from operator import length_hint 
import torch

In [15]:
traindata, validdata, testdata = get_dataloader('data/sarcasm/sarcasm.pkl', data_type='sarcasm')
text_file_pkl = open('data/sarcasm/sarcasm_raw_text.pkl','rb')
text_file = pickle.load(text_file_pkl)

#### Data structure

##### max_pad = False

In [2]:
iter_ = next(iter(traindata))

In [14]:
print("audio, visual, language of examples in the first batch")
for i in [0, 1, 2]:
  print(iter_[0][i].shape)
print("\n")

print("audio information of the first instance in the first batch") 
print(iter_[0][0][0].shape)
print("\n")

# the actual length of each example in the batch without padding
print("processed_input_lengths")
print(iter_[1][0])
print("\n")

print("pytorch index of  each example in the entire dataset")
print(iter_[2].shape)
print("\n")

print("label for examples in each batch")
print(iter_[3].shape)
print("\n")

print("Index for sentences in each batch")
print(iter_[4])
print("\n")


audio, visual, language of examples in the first batch
torch.Size([32, 26, 371])
torch.Size([32, 26, 81])
torch.Size([32, 26, 300])


audio information of the first instance in the first batch
torch.Size([26, 371])


processed_input_lengths
tensor([12, 16, 10, 10,  8,  9, 11,  9,  3,  7, 26, 17,  1, 22,  9,  5, 12, 10,
        10, 14,  6, 23, 14,  9, 15,  9,  6, 14, 10,  6, 20,  9])


pytorch index of  each example in the entire dataset
torch.Size([32, 1])


label for examples in each batch
torch.Size([32, 1])


Index for sentences in each batch
['1_6221', '1_7675', '2_257', '1_3177', '2_66', '1_2464', '2_137', '2_375', '2_86', '1_7357', '2_167', '2_594', '2_264', '1_5699', '2_599', '2_89', '1_5109', '1_1189', '2_9', '2_151', '2_194', '1_12275', '1_10004', '2_84', '2_338', '1_10977', '2_74', '1_11322', '2_3', '2_585', '2_317', '2_287']




##### max_pad = True

In [39]:
traindata, validdata, testdata = get_dataloader('data/sarcasm/sarcasm.pkl', max_pad = True, data_type='sarcasm')
iter_ = next(iter(traindata))

In [41]:
iter_[-2]

tensor([[ 1.],
        [-1.],
        [ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.],
        [ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [ 1.],
        [-1.],
        [ 1.],
        [-1.],
        [-1.],
        [ 1.],
        [-1.],
        [-1.],
        [-1.],
        [ 1.],
        [-1.]])

In [7]:
print("audio, visual, language of examples in the first batch")
for i in [0, 1, 2]:
  print(iter_[i].shape)
print("\n")

print("audio information of the first instance in the first batch") 
print(iter_[0][1].shape)
print("\n")


print("label for each sentence in each batch")
print(iter_[3].shape)
print("\n")

print("Index for each sentence in each batch")
print(iter_[4])
print("\n")

audio, visual, language of examples in the first batch
torch.Size([32, 50, 371])
torch.Size([32, 50, 81])
torch.Size([32, 50, 300])


audio information of the first instance in the first batch
torch.Size([50, 371])


label for each sentence in each batch
torch.Size([32, 1])


Index for each sentence in each batch
['2_74', '2_246', '1_11242', '2_131', '1_6769', '1_8159', '1_276', '2_316', '1_8042', '1_5699', '2_495', '2_477', '1_7575', '2_226', '1_3256', '1_3069', '1_2669', '2_33', '1_1262', '2_161', '2_172', '1_3293', '2_343', '1_11924', '1_9003', '1_1180', '1_2819', '2_559', '1_1185', '2_430', '2_377', '2_438']




#### Modifying sentences

##### max_pad = False

In [16]:
iter_ = next(iter(traindata))

In [176]:
torch.zeros(iter_[0][2][0][-1].shape)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [175]:
iter_[0][2][0][-1].shape

torch.Size([300])

In [145]:
np.delete(iter_[0][1][0],[1,2],0).shape

torch.Size([35, 81])

In [19]:
def pick_word_rand(label, len_sent):
    replace_term = round(len_sent * 0.1)
    return random.sample(range(0, len_sent), replace_term)

In [150]:
for iter_ in traindata:
    for idx, label_sent in enumerate(iter_[-1]):
        len_sent = length_hint(text_file[label_sent])
        if len_sent >= 10:
            word_index = pick_word_rand(label_sent, len_sent)
            vision_sent = iter_[0][0][idx]
            audio_sent = iter_[0][1][idx]
            text_sent = iter_[0][2][idx]
            print(idx, len_sent, word_index)
            # print(idx, len_sent)
            # count_10 += 1

            # np.delete(a, [1,2,3], 1)
    break

0 11 [1] torch.Size([29, 300])
1 17 [2, 7] torch.Size([29, 300])
2 14 [5] torch.Size([29, 300])
3 10 [0] torch.Size([29, 300])
5 13 [7] torch.Size([29, 300])
6 12 [7] torch.Size([29, 300])
7 13 [6] torch.Size([29, 300])
8 12 [8] torch.Size([29, 300])
9 16 [8, 14] torch.Size([29, 300])
12 10 [4] torch.Size([29, 300])
13 13 [8] torch.Size([29, 300])
14 19 [11, 2] torch.Size([29, 300])
15 21 [4, 1] torch.Size([29, 300])
16 10 [8] torch.Size([29, 300])
17 11 [0] torch.Size([29, 300])
19 29 [5, 4, 21] torch.Size([29, 300])
20 27 [22, 25, 6] torch.Size([29, 300])
21 19 [17, 16] torch.Size([29, 300])
22 29 [12, 11, 2] torch.Size([29, 300])
23 13 [0] torch.Size([29, 300])
25 10 [0] torch.Size([29, 300])
26 11 [6] torch.Size([29, 300])
28 25 [13, 17] torch.Size([29, 300])
29 15 [12, 2] torch.Size([29, 300])


In [242]:
vison_batch = []
audio_batch = []
text_batch = []

for idx, label_sent in enumerate(iter_[-1]):
    len_sent = length_hint(text_file[label_sent])
    
    
    # For each sentence that lengths greater than 10, we modify the sentence
    if len_sent >= 10:
        print(iter_[1][idx])
        
        # Retuen index for the words in a sentence that need to be changed 
        word_index = pick_word_rand(label_sent, len_sent)

        # Delete words and pad for each modality: vision, audio and text
        for num in range(3):
            original_sent = iter_[0][num][idx]

            # delete
            modify_sent = np.delete(original_sent,word_index, 0)

            # pad
            pad_sent = torch.zeros(length_hint(word_index), modify_sent.shape[1])
            final_sent = torch.cat((modify_sent, pad_sent), 0)

            # concatenate
            if num == 0:
                vison_batch.append(final_sent.tolist())
            elif num == 1:
                audio_batch.append(final_sent.tolist())
            else:
                text_batch.append(final_sent.tolist())

    # otherwise, we use the original embedding
    else:
        vison_batch.append(iter_[0][0][idx])
        audio_batch.append(iter_[0][1][idx])
        text_batch.append(iter_[0][2][idx])

        
print(torch.tensor(vison_batch).shape)
        

torch.Size([32, 29, 371])


In [250]:
iter_[1]

[tensor([11, 17, 14, 10,  9, 13, 12, 13, 12, 15,  8,  1, 10, 13, 19, 21, 10, 11,
          4, 29, 27, 19, 29, 13,  9, 10, 11,  5, 25, 15,  7,  7]),
 tensor([11, 17, 14, 10,  9, 13, 12, 13, 12, 15,  8,  1, 10, 13, 19, 21, 10, 11,
          4, 29, 27, 19, 29, 13,  9, 10, 11,  5, 25, 15,  7,  7]),
 tensor([11, 17, 14, 10,  9, 13, 12, 13, 12, 15,  8,  1, 10, 13, 19, 21, 10, 11,
          4, 29, 27, 19, 29, 13,  9, 10, 11,  5, 25, 15,  7,  7])]

In [248]:
text_file["2_474"]

['Lovely']

##### max_pad = True

In [18]:
traindata, validdata, testdata = get_dataloader('data/sarcasm/sarcasm.pkl', max_pad=True ,data_type='sarcasm')
iter_ = next(iter(traindata))

In [38]:
traindata

In [27]:
vison_batch = []
audio_batch = []
text_batch = []

for idx, label_sent in enumerate(iter_[-1]):
    len_sent = length_hint(text_file[label_sent])
    
    # If the length of each sentence is less than 10, we use the original embedding.
    if len_sent < 10:
        vison_batch.append(iter_[0][idx])
        audio_batch.append(iter_[1][idx])
        text_batch.append(iter_[2][idx])
    
    # We we modify the sentence
    else:
        # Retuen index for the words in a sentence that need to be changed 
        word_index = pick_word_rand(label_sent, len_sent)
        print(word_index, len_sent)
        
        # Delete words and pad for each modality: vision, audio and text
        for num in range(3):
            original_sent = iter_[num][idx]
            
            # delete
            modify_sent = np.delete(original_sent,word_index, 0)

            # pad
            pad_sent = torch.zeros(length_hint(word_index), modify_sent.shape[1])
            final_sent = torch.cat((modify_sent, pad_sent), 0)

            # concatenate
            if num == 0:
                vison_batch.append(final_sent.tolist())
            elif num == 1:
                audio_batch.append(final_sent.tolist())
            else:
                text_batch.append(final_sent.tolist())

[2] 10
[2] 14
[17, 1] 18
[8, 4] 22
[2, 14] 16
[12, 6] 17
[5] 12
[5] 10
[9] 11
[6] 14
[10, 0] 19
[8] 14
[16, 12] 21
[3, 13] 17
[9, 8] 18
[9] 13
[2] 11
[16, 20, 2] 26
[0] 11
